### ISSUE TITLE
Uncaught TypeError: target.getModel is not a function

### ISSUE THREAD

**Issue by kaaloo** [atom-haskell/ide-haskell-repl#15]
[Enter steps to reproduce below:]
1. Use the Toggle Haskell Repl command

**Atom Version**: 1.3.2
**System**: Ubuntu 15.10
**Thrown From**: [ide-haskell-repl](https://github.com/atom-haskell/ide-haskell-repl) package, v0.0.12
### Stack Trace

Uncaught TypeError: target.getModel is not a function

```
At /home/luis/.atom/packages/ide-haskell-repl/lib/ide-haskell-repl.coffee:40

TypeError: target.getModel is not a function
    at atom-text-editor.disposables.add.atom.commands.add.ide-haskell-repl:toggle (/home/luis/.atom/packages/ide-haskell-repl/lib/ide-haskell-repl.coffee:40:22)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:06.6.0 command-palette:toggle (input.hidden-input)
     -0:02.3.0 core:move-down (input.hidden-input)
     -0:00.8.0 core:confirm (input.hidden-input)
     -0:00.8.0 ide-haskell-repl:toggle (input.hidden-input)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      "hidpi"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Parinfer, v1.2.0
Stylus, v1.2.1
atom-grails, v0.1.0
fonts, v1.0.0
ide-haskell, v1.3.8
ide-haskell-repl, v0.0.12
language-babel, v2.6.3
language-clojure, v0.19.1
language-elm, v1.3.0
language-erlang, v3.0.0
language-groovy, v0.5.0
language-haskell, v1.5.1
language-lua, v0.9.4
language-purescript, v0.6.1
language-scheme, v1.4.0
linter, v1.11.3
linter-elm-make, v0.4.0
react, v0.12.10
term3, v0.21.0

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
Can't reproduce.

Besides, this shouldn't be possible: since command is bound to `atom-text-editor`, `target` _has_ to be an instance of `EditorElement`, which _does_ have `getModel` method.

So I have no idea how you managed to get this.

**Comment by kaaloo** [comment]
Here's a screenshot, what I see is that the target parameter is undefined!  That is really weird because the caller definitely passes currentTarget and it looks fine (see second screenshot).

![test hs - -home-luis-code-haskell-hacking-haskell-programming - atom_018](https://cloud.githubusercontent.com/assets/67010/12071354/bb6963e2-b0a7-11e5-970f-ef1e1aaac152.jpg)

![test hs - -home-luis-code-haskell-hacking-haskell-programming - atom_019](https://cloud.githubusercontent.com/assets/67010/12071355/c6b920a2-b0a7-11e5-80bf-ccafa8d77df5.jpg)

**Comment by kaaloo** [comment]
Oh wait I do see what's going on, this is actually referring to `atom-text-editor` instead of `target` which is `undefined`.  I'll try tweaking `ide-haskell-repl.coffee` by using this instead of `target` in the `getModel()` call to see if that helps.

**Comment by lierdakil** [comment]
currentTarget is bound as this. Parameter is actually dispatchedEvent. It
should be Object-like with a property 'target'.

Here's a screenshot, what I see is that the target parameter is undefined!
That is really weird because the caller definitely passes currentTarget and
it looks fine (see second screenshot).

[image: test hs - -home-luis-code-haskell-hacking-haskell-programming -
atom_018]
https://cloud.githubusercontent.com/assets/67010/12071354/bb6963e2-b0a7-11e5-970f-ef1e1aaac152.jpg

[image: test hs - -home-luis-code-haskell-hacking-haskell-programming -
atom_019]
https://cloud.githubusercontent.com/assets/67010/12071355/c6b920a2-b0a7-11e5-80bf-ccafa8d77df5.jpg

**Comment by kaaloo** [comment]
Ok bingo, so it doesn't have a `target` property afaict.

![test hs - -home-luis-code-haskell-hacking-haskell-programming - atom_020](https://cloud.githubusercontent.com/assets/67010/12071366/f039f6d0-b0a8-11e5-8602-f6f49767bdcf.jpg)

**Comment by lierdakil** [comment]
If it didn't, the error should've been 'cannot get property getModel of
undefined', not 'getModel is not a function'... Frankly, I'm baffled.
1 янв. 2016 г. 18:59 пользователь "Luis Arias" notifications@github.com
написал:

**Comment by kaaloo** [comment]
Ok I'm starting with a clean `.atom` directory and I can confirm that with just the
- ide-haskell
- ide-haskell-repl
- language-haskell

packages installed the repl comes up fine.  I'll install my previous packages little by little to try and figure out which one is causing an issue.

**Comment by kaaloo** [comment]
Closing this because it must have been something in my config.  Sorry for the disturbance!
