### ISSUE TITLE
Uncaught Error: Unknown builder undefined

### ISSUE THREAD

**Issue by nasagfunaro** [atom-haskell/ide-haskell-repl#28]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.9.9
**System**: Mac OS X 10.11.5
**Thrown From**: [ide-haskell-repl](https://github.com/atom-haskell/ide-haskell-repl) package, v0.1.0
### Stack Trace

Uncaught Error: Unknown builder undefined

```
At /Users/gfunaro/.atom/packages/ide-haskell-repl/lib/ide-haskell-repl-view.coffee:100

Error: Unknown builder undefined
    at /Users/gfunaro/.atom/packages/ide-haskell-repl/lib/ide-haskell-repl-view.coffee:100:45
    at IdeHaskellReplView.module.exports.IdeHaskellReplView.runREPL (/Users/gfunaro/.atom/packages/ide-haskell-repl/lib/ide-haskell-repl-view.coffee:100:35)
    at Immediate._onImmediate (/Users/gfunaro/.atom/packages/ide-haskell-repl/lib/ide-haskell-repl-view.coffee:71:10)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
```
### Commands

```
     -0:18.2.0 editor:newline-below (atom-text-editor.editor.is-focused)
     -0:16.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:00.3.0 ide-haskell-repl:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-haskell, v0.6.6 (active)
haskell-ghc-mod, v1.17.2 (active)
ide-haskell, v1.7.1 (active)
ide-haskell-repl, v0.1.0 (active)
language-cup, v1.1.2 (active)
language-cypher, v0.3.0 (active)
language-haskell, v1.9.7 (active)
language-sml, v0.6.0 (active)
my-theme-syntax, v0.0.0 (inactive)
pretty-json, v1.6.0 (active)
seti-syntax, v1.0.1 (inactive)
seti-ui, v1.3.2 (active)
seti-ui-red, v0.13.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (active)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.1 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.1 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
Hopefully fixed by v0.1.1. Note that settings format changed in v0.1.0. Thanks for reporting.

**Comment by cameron-martin** [comment]
I'm still getting this error on the latest version (0.3.1)

**Comment by lierdakil** [comment]
@cameron-martin, please post atom error report.

To copy Atom's error report to clipboard:
![atom-report](https://cloud.githubusercontent.com/assets/7275622/19539919/bf17df84-9664-11e6-873a-cba249acaa88.png)

**Comment by cameron-martin** [comment]
[Enter steps to reproduce below:]
1. Open the repl

**Atom Version**: 1.8.0
**System**: Ubuntu 16.04.1
**Thrown From**: [ide-haskell-repl](https://github.com/atom-haskell/ide-haskell-repl) package, v0.1.0

### Stack Trace

Uncaught Error: Unknown builder undefined

```
At /home/cameron/.atom/packages/ide-haskell-repl/lib/ide-haskell-repl-view.coffee:100

Error: Unknown builder undefined
    at /home/cameron/.atom/packages/ide-haskell-repl/lib/ide-haskell-repl-view.coffee:100:45
    at IdeHaskellReplView.module.exports.IdeHaskellReplView.runREPL (/home/cameron/.atom/packages/ide-haskell-repl/lib/ide-haskell-repl-view.coffee:100:35)
    at Immediate._onImmediate (/home/cameron/.atom/packages/ide-haskell-repl/lib/ide-haskell-repl-view.coffee:71:10)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

### Commands

```
     -5:12.7.0 snippets:expand (atom-text-editor.editor.is-focused)
     -5:12.7.0 editor:indent (atom-text-editor.editor.is-focused)
 10x -4:54.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:51.5.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  8x -4:50.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:48.7.0 core:move-left (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:48.5.0 core:move-right (atom-text-editor.editor.is-focused)
     -4:48.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -4:47.7.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -4:47.7.0 snippets:expand (atom-text-editor.editor.is-focused)
     -4:47.7.0 editor:indent (atom-text-editor.editor.is-focused)
     -3:50.6.0 core:select-all (atom-text-editor.editor.is-focused)
     -3:50.3.0 core:copy (atom-text-editor.editor.is-focused)
     -3:41.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:39.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:01.1.0 ide-haskell-repl:toggle (atom-text-editor.editor.is-focused)
```

### Config

``` json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "ide-flow",
      "haskell-grammar",
      "linter",
      "docblockr",
      "nuclide"
    ],
    "themes": [
      "atom-material-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
atom-material-ui, v1.3.6
autocomplete-haskell, v0.6.7
color-picker, v2.2.2
haskell-ghc-mod, v1.18.0
haskell-pointfree, v0.1.3
highlight-selected, v0.11.2
ide-haskell, v1.8.1
ide-haskell-cabal, v1.6.4
ide-haskell-hasktags, v0.0.7
ide-haskell-repl, v0.1.0
language-babel, v2.45.0
language-coq, v0.1.0
language-haskell, v1.9.9
language-idris, v0.4.5
language-ini, v1.16.0
language-ocaml, v1.1.2
language-swift, v0.4.0
language-thrift, v1.0.2
linter-eslint, v7.3.2
merge-conflicts, v1.4.4
tool-bar, v1.0.1

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
@cameron-martin, apparently you're still using v0.1.0. Newer versions of ide-haskell-repl require Atom v1.9.0, so that is probably the reason why.
