### ISSUE TITLE
Uncaught Error: write EPIPE

### ISSUE THREAD

**Issue by totano** [atom-haskell/ide-haskell-repl#4]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Microsoft Windows 10 Pro
**Thrown From**: [ide-haskell-repl](https://github.com/atom-haskell/ide-haskell-repl) package, v0.0.3
### Stack Trace

Uncaught Error: write EPIPE

```
At events.js:141

Error: write EPIPE
  at exports._errnoException (util.js:814:11)
  at Socket._writeGeneric (net.js:672:26)
  at Socket._write (net.js:691:8)
  at doWrite (_stream_writable.js:291:12)
  at writeOrBuffer (_stream_writable.js:277:5)
  at Socket.Writable.write (_stream_writable.js:206:11)
  at Socket.write (net.js:615:40)
  at new GHCI (C:\Users\aless\.atom\packages\ide-haskell-repl\lib\ghci.coffee:59:17)
  at new IdeHaskellReplView (C:\Users\aless\.atom\packages\ide-haskell-repl\lib\ide-haskell-repl-view.coffee:55:17)
  at C:\Users\aless\.atom\packages\ide-haskell-repl\lib\ide-haskell-repl.coffee:39:11
  at Workspace.module.exports.Workspace.openURIInPane (C:\Users\aless\AppData\Local\atom\app-1.1.0\resources\app.asar\src\workspace.js:431:22)
  at Workspace.module.exports.Workspace.open (C:\Users\aless\AppData\Local\atom\app-1.1.0\resources\app.asar\src\workspace.js:374:19)
  at Object.module.exports.IdeHaskellRepl.open (C:\Users\aless\.atom\packages\ide-haskell-repl\lib\ide-haskell-repl.coffee:56:20)
  at atom-text-editor.disposables.add.atom.commands.add.ide-haskell-repl:toggle (C:\Users\aless\.atom\packages\ide-haskell-repl\lib\ide-haskell-repl.coffee:43:10)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\aless\AppData\Local\atom\app-1.1.0\resources\app.asar\src\command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (C:\Users\aless\AppData\Local\atom\app-1.1.0\resources\app.asar\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\aless\AppData\Local\atom\app-1.1.0\resources\app.asar\src\command-registry.js:143:19)
  at EventEmitter.module.exports.WindowEventHandler.handleIPCCommand (C:\Users\aless\AppData\Local\atom\app-1.1.0\resources\app.asar\src\window-event-handler.js:213:28)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:169:7)

```
### Commands

```
  2x -0:12.4.0 ide-haskell-repl:toggle (div.panels-item)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "atom-light-syntax"
    ]
  },
  "ide-haskell-repl": {}
}
```
### Installed Packages

``` coffee
# User
autocomplete-haskell, v0.6.1
haskell-ghc-mod, v1.1.1
ide-haskell, v1.3.0
ide-haskell-cabal, v1.0.0
ide-haskell-repl, v0.0.3
language-haskell, v1.4.12

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
Seems like ghci either failed to spawn or crashed immediately after launch.

v0.0.4 should give a more readable error message in this case.

If you need further help, feel free to file a new issue.
