### ISSUE TITLE
Uncaught TypeError: invalid pid

### ISSUE THREAD

**Issue by nchiappari** [atom-haskell/ide-haskell-repl#50]
[Enter steps to reproduce:]

1. install ide-haskell-repl package
2. close installation tab in atom

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [ide-haskell-repl](https://github.com/atom-haskell/ide-haskell-repl) package 0.6.0

### Stack Trace

Uncaught TypeError: invalid pid

```
At /Users/nicholaschiappari/.atom/packages/ide-haskell-repl/node_modules/tree-kill/index.js:58

TypeError: invalid pid
    at process.kill (internal/process.js:155:13)
    at killPid (/packages/ide-haskell-repl/node_modules/tree-kill/index.js:68:17)
    at /packages/ide-haskell-repl/node_modules/tree-kill/index.js:50:17
    at Array.forEach (native)
    at killAll (/packages/ide-haskell-repl/node_modules/tree-kill/index.js:42:27)
    at /packages/ide-haskell-repl/node_modules/tree-kill/index.js:21:13
    at ChildProcess.onClose (/packages/ide-haskell-repl/node_modules/tree-kill/index.js:89:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
  2x -1:30.8.0 settings-view:check-for-package-updates (atom-pane.pane.active)
  2x -0:57.2.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-python 1.8.63 
ide-haskell 1.9.6 
ide-haskell-repl 0.6.0 
language-haskell 1.12.1 
```

**Comment by lierdakil** [comment]
Thanks for reporting, sorry nobody reacted sooner. Pretty sure this was fixed somewhere along the way in v0.7.0. Please let us know if not.
