### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by findpikachu** [atom-haskell/ide-haskell-repl#54]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [ide-haskell-repl](https://github.com/atom-haskell/ide-haskell-repl) package 0.7.3

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\Users\Administrator\.atom\packages\ide-haskell-repl\node_modules\etch\lib\patch.js:60

TypeError: Cannot read property 'length' of undefined
    at updateChildren (/packages/ide-haskell-repl/node_modules/etch/lib/patch.js:60:32)
    at patch (/packages/ide-haskell-repl/node_modules/etch/lib/patch.js:18:9)
    at updateChildren (/packages/ide-haskell-repl/node_modules/etch/lib/patch.js:77:7)
    at patch (/packages/ide-haskell-repl/node_modules/etch/lib/patch.js:18:9)
    at updateChildren (/packages/ide-haskell-repl/node_modules/etch/lib/patch.js:77:7)
    at patch (/packages/ide-haskell-repl/node_modules/etch/lib/patch.js:18:9)
    at updateSync (/packages/ide-haskell-repl/node_modules/etch/lib/component-helpers.js:116:20)
    at /packages/ide-haskell-repl/node_modules/etch/lib/component-helpers.js:72:7
    at DefaultScheduler.performUpdates (/packages/ide-haskell-repl/node_modules/etch/lib/default-scheduler.js:48:34)
```

### Commands

```
  2x -0:32.8.0 ide-haskell-repl:toggle (atom-pane.pane.active)
     -0:15.2.0 ide-haskell-repl:reload-repeat (atom-text-editor.editor.ide-haskell-repl)
```

### Non-Core Packages

```
autocomplete-elixir 1.5.16 
autocomplete-haskell 0.7.2 
busy-signal 1.4.3 
haskell-ghc-mod 1.19.9 
ide-haskell-repl 0.7.3 
intentions 1.1.5 
language-elixir 0.20.3 
language-haskell 1.14.3 
linter 2.2.0 
linter-elixirc 1.7.0 
linter-hlint 2.0.0 
linter-ui-default 1.2.4 
script 3.17.3 
```

**Comment by lierdakil** [comment]
Thanks for reporting.
