### ISSUE TITLE
Failed to activate the ide-haskell-repl package

### ISSUE THREAD

**Issue by willbasky** [atom-haskell/ide-haskell-repl#57]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.0 x64
**Electron**: 1.6.15
**OS**: Linux Mint
**Thrown From**: [ide-haskell-repl](https://github.com/atom-haskell/ide-haskell-repl) package 0.7.7

### Stack Trace

Failed to activate the ide-haskell-repl package

```
At Cannot find module 'tslib'

Error: Cannot find module 'tslib'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/ide-haskell-repl/lib/ide-haskell-repl.js:3:17)
    at /packages/ide-haskell-repl/lib/ide-haskell-repl.js:183:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:937:35)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:244:22)
    at /usr/share/atom/resources/app/src/package.js:1068:34
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PackageManager.triggerDeferredActivationHooks (/usr/share/atom/resources/app/src/package-manager.js:717:40)
    at Promise.all.then (/usr/share/atom/resources/app/src/package-manager.js:650:18)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atomic-emacs 0.12.1 
autocomplete-haskell 1.0.1 
file-icons 2.1.14 
fonts 3.0.3 
haskell-ghc-mod 2.1.3 
haskell-pointfree 0.2.0 
ide-haskell 2.2.0 
ide-haskell-cabal 2.0.5 
ide-haskell-hasktags 0.0.12 
ide-haskell-hoogle 0.1.2 
ide-haskell-repl 0.7.7 
language-haskell 1.15.0 
minimap 4.29.7 
term3 0.22.1 
tidal-autocode 0.6.4 
tidalcycles 0.9.4 
```

**Comment by lierdakil** [comment]
Sorry, I messed up. v0.7.8 should be fine.

**Comment by willbasky** [comment]
I ` ve updated to  v0.7.8 and it is going well.

**Comment by marcusegues** [comment]
I have this issue as well on Atom 1.26.1 and  ide-haskell-repl 0.8.0...

**Comment by lierdakil** [comment]
Open a new issue with full diagnostics, because it's different. Please don't hijack old resolved issues.

Most likely, something borked during installation, try reinstalling the package.
