### ISSUE TITLE
Error: Process destroyed while awaiting stream readable

### ISSUE THREAD

**Issue by Kratosfm** [atom-haskell/ide-haskell-repl#70]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Mac OS X 10.14.3
**Thrown From**: [ide-haskell-repl](https://github.com/atom-haskell/ide-haskell-repl) package 0.8.4

### Stack Trace

Error: Process destroyed while awaiting stream readable

```
At Error: Process destroyed while awaiting stream readable

Error: Process destroyed while awaiting stream readable
    at EventEmitter.rejectError (/packages/ide-haskell-repl/lib/interactive-process.js:178:24)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at EventEmitter.emit (events.js:208:7)
    at InteractiveProcess.destroy (/packages/ide-haskell-repl/lib/interactive-process.js:152:21)
    at GHCI.destroy (/packages/ide-haskell-repl/lib/ghci.js:65:22)
    at GHCI.didExit (/packages/ide-haskell-repl/lib/ghci.js:69:14)
    at ChildProcess.InteractiveProcess.process.on (/packages/ide-haskell-repl/lib/interactive-process.js:31:17)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

### Commands

```
     -3:15.1.0 core:save (input.hidden-input)
     -2:00.1.0 haskell-ghc-mod:check-file (input.hidden-input)
  2x -1:50.6.0 ide-haskell-repl:ghci-interrupt (atom-text-editor.editor.ide-haskell-repl)
     -1:40.2.0 ide-haskell:toggle-output (input.hidden-input)
     -1:37.4.0 haskell-ghc-mod:check-file (atom-pane.pane.active)
     -1:34.3.0 ide-haskell-cabal:build (atom-pane.pane.active)
     -1:21.7.0 ide-haskell-cabal:test (input.hidden-input)
     -1:14 ide-haskell-cabal:deps (input.hidden-input)
     -1:09.5.0 ide-haskell-cabal:test (input.hidden-input)
     -1:07.1.0 ide-haskell-repl:toggle (input.hidden-input)
  3x -0:56.9.0 core:backspace (input.hidden-input)
     -0:53 editor:newline (input.hidden-input)
  4x -0:52 core:backspace (input.hidden-input)
     -0:50.4.0 editor:newline (input.hidden-input)
     -0:49.6.0 core:backspace (input.hidden-input)
 10x -0:48.7.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
atom-html-preview 0.2.6 
haskell-ghc-mod 2.2.4 
ide-haskell 2.4.0 
ide-haskell-cabal 2.2.1 
ide-haskell-repl 0.8.4 
language-haskell 1.18.0 
term3 0.22.1 
```

**Comment by lierdakil** [comment]
Hi. Sorry for the belated response.

This most likely means that ghci process crashed for one reason or another. More information is probably available in the dev. console (View → Developer → Toggle Developer Tools → Console). If it's a cabal/stack project, the first thing to do is to try to build it and fix any "external" errors that show up (i.e. those that aren't directly in the project code) -- there's a decent chance something like a dependency is missing, and automatics can't handle it.

So, either that, or you've just ran into a particular race condition that occurs when you rapidly open and then close the REPL window -- which is not really a bug as far as I'm concerned, tbh, since everything actually works as expected except a pesky error message.

If it's neither, and you could provide some reproduction instructions, that would be great. Thanks in advance.
