### ISSUE TITLE
Error: Process destroyed while awaiting stream readable

### ISSUE THREAD

**Issue by UoE-Zhang-Zijie** [atom-haskell/ide-haskell-repl#75]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.51.0 x64
**Electron**: 5.0.13
**OS**: Unknown Windows version
**Thrown From**: [ide-haskell-repl](https://github.com/atom-haskell/ide-haskell-repl) package 0.10.0

### Stack Trace

Error: Process destroyed while awaiting stream readable

```
At Error: Process destroyed while awaiting stream readable

Error: Process destroyed while awaiting stream readable
    at EventEmitter.rejectError (/packages/ide-haskell-repl/lib/interactive-process.js:186:24)
    at Object.onceWrapper (events.js:282:20)
    at EventEmitter.emit (events.js:199:15)
    at InteractiveProcess.destroy (/packages/ide-haskell-repl/lib/interactive-process.js:159:21)
    at GHCI.destroy (/packages/ide-haskell-repl/lib/ghci.js:65:22)
    at GHCI.didExit (/packages/ide-haskell-repl/lib/ghci.js:69:14)
    at /packages/ide-haskell-repl/lib/interactive-process.js:36:17)
    at ChildProcess.emit (events.js:194:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
```

### Commands

```
     -5:01.7.0 settings-view:install-packages-and-themes (div.welcome.is-guide)
  2x -4:50.8.0 core:paste (input.hidden-input)
     -3:28.9.0 core:backspace (input.hidden-input)
     -3:21.3.0 core:paste (input.hidden-input)
     -3:20.2.0 core:backspace (input.hidden-input)
     -3:11.6.0 core:paste (input.hidden-input)
     -3:09.7.0 core:backspace (input.hidden-input)
     -2:59.3.0 core:paste (input.hidden-input)
     -2:58.6.0 core:backspace (input.hidden-input)
     -2:43.9.0 settings-view:uninstall-packages (input.hidden-input)
     -2:14.5.0 application:open-file (input.hidden-input)
     -1:37.3.0 ide-haskell-repl:toggle (input.hidden-input)
     -0:14.6.0 haskell-ghc-mod:check-file (input.hidden-input)
     -0:09.7.0 ide-haskell-repl:toggle (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-haskell 1.0.1 
haskell-ghc-mod 2.2.6 
ide-haskell 2.4.1 
ide-haskell-cabal 2.5.0 
ide-haskell-repl 0.10.0 
language-haskell 1.20.0 
```

**Comment by lierdakil** [comment]
Long story short, GHCi crashed. More information should be available in other pop-up messages if there are any. Since I don't know anything about your setup and where you encountered this error, I can not say much more than that. If this is a one-off crash, it's safe to ignore. If you need help, please explain what you did, and what was the expected result.
